"""Run local QuantConnect LEAN backtests via the lean CLI (Docker on Mac)."""

from __future__ import annotations

import asyncio
import json
import logging
import shutil
import subprocess
import tempfile
from datetime import datetime
from pathlib import Path
from typing import Any

from config import settings

logger = logging.getLogger(__name__)

PROJECT_NAME = "IQTBacktest"
STRATEGIES = frozenset(
    {"rsi_mean_reversion", "ma_crossover", "macd_momentum", "bollinger_bands"}
)


def _workspace_root() -> Path:
    return Path(settings.lean_workspace_dir).resolve()


def _project_dir() -> Path:
    return _workspace_root() / PROJECT_NAME


def _parse_date(value: str) -> tuple[int, int, int]:
    dt = datetime.strptime(value, "%Y-%m-%d")
    return dt.year, dt.month, dt.day


def _lean_executable() -> str | None:
    if settings.lean_cli_path:
        path = Path(settings.lean_cli_path)
        if path.is_file():
            return str(path)
    return shutil.which("lean")


def _docker_running() -> bool:
    try:
        result = subprocess.run(
            ["docker", "info"],
            capture_output=True,
            text=True,
            timeout=15,
        )
        return result.returncode == 0
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False


def _credentials_configured() -> bool:
    creds = Path.home() / ".lean" / "credentials"
    if not creds.is_file():
        return False
    text = creds.read_text(encoding="utf-8")
    return "user-id" in text and "api-token" in text


def get_status() -> dict[str, Any]:
    workspace = _workspace_root()
    lean_json = workspace / "lean.json"
    project = _project_dir() / "main.py"
    lean_cli = _lean_executable()
    docker_ok = _docker_running()
    workspace_ready = lean_json.is_file() and project.is_file()
    creds = _credentials_configured()

    available = bool(lean_cli and docker_ok and workspace_ready)
    if not lean_cli:
        message = "LEAN CLI not found. Run: ./scripts/setup-lean-mac.sh"
    elif not docker_ok:
        message = "Docker is not running. Start Docker Desktop, then retry."
    elif not workspace_ready:
        message = "LEAN workspace not initialized. Run: ./scripts/setup-lean-mac.sh"
    elif not creds:
        message = (
            "LEAN is ready for sample data. For other symbols/dates, add QuantConnect "
            "credentials via lean login (free account at quantconnect.com)."
        )
    else:
        message = "LEAN engine ready for local backtests."

    return {
        "available": available,
        "docker_running": docker_ok,
        "lean_cli": bool(lean_cli),
        "workspace_ready": workspace_ready,
        "credentials_configured": creds,
        "workspace_path": str(workspace),
        "message": message,
    }


def _algorithm_source(
    symbol: str,
    strategy: str,
    start_date: str,
    end_date: str,
    initial_capital: float,
) -> str:
    sy, sm, sd = _parse_date(start_date)
    ey, em, ed = _parse_date(end_date)
    cash = int(initial_capital)

    header = f'''# region imports
from AlgorithmImports import *
# endregion


class IQTBacktest(QCAlgorithm):
    """Generated by Integrated Quant Terminal — {strategy} on {symbol}."""

    def initialize(self) -> None:
        self.set_start_date({sy}, {sm}, {sd})
        self.set_end_date({ey}, {em}, {ed})
        self.set_cash({cash})
        self.set_benchmark("{symbol}")
        self._symbol = self.add_equity("{symbol}", Resolution.Daily).symbol
'''

    if strategy == "rsi_mean_reversion":
        body = '''
        self._rsi = self.rsi(self._symbol, 14, MovingAverageType.Wilders, Resolution.Daily)
        self._prev_rsi = None

    def on_data(self, data: Slice) -> None:
        if not self._rsi.is_ready:
            return
        rsi = float(self._rsi.current.value)
        if self._prev_rsi is None:
            self._prev_rsi = rsi
            return
        if rsi < 30 and self._prev_rsi >= 30 and not self.portfolio.invested:
            self.set_holdings(self._symbol, 1)
        elif rsi > 70 and self._prev_rsi <= 70 and self.portfolio.invested:
            self.liquidate()
        self._prev_rsi = rsi
'''
    elif strategy == "ma_crossover":
        body = '''
        self._fast = self.ema(self._symbol, 50, Resolution.Daily)
        self._slow = self.ema(self._symbol, 200, Resolution.Daily)

    def on_data(self, data: Slice) -> None:
        if not self._fast.is_ready or not self._slow.is_ready:
            return
        if self._fast.current.value > self._slow.current.value and not self.portfolio.invested:
            self.set_holdings(self._symbol, 1)
        elif self._fast.current.value < self._slow.current.value and self.portfolio.invested:
            self.liquidate()
'''
    elif strategy == "macd_momentum":
        body = '''
        self._macd = self.macd(self._symbol, 12, 26, 9, MovingAverageType.Exponential, Resolution.Daily)
        self._was_above = None

    def on_data(self, data: Slice) -> None:
        if not self._macd.is_ready:
            return
        macd = float(self._macd.current.value)
        signal = float(self._macd.signal.current.value)
        above = macd > signal
        if self._was_above is None:
            self._was_above = above
            return
        if above and not self._was_above and not self.portfolio.invested:
            self.set_holdings(self._symbol, 1)
        elif not above and self._was_above and self.portfolio.invested:
            self.liquidate()
        self._was_above = above
'''
    elif strategy == "bollinger_bands":
        body = '''
        self._bb = self.bb(self._symbol, 20, 2, MovingAverageType.Simple, Resolution.Daily)
        self._prev_close = None

    def on_data(self, data: Slice) -> None:
        if not self._bb.is_ready:
            return
        if not data.bars.contains_key(self._symbol):
            return
        close = float(data.bars[self._symbol].close)
        lower = float(self._bb.lower_band.current.value)
        upper = float(self._bb.upper_band.current.value)
        if self._prev_close is None:
            self._prev_close = close
            return
        if close < lower and self._prev_close >= lower and not self.portfolio.invested:
            self.set_holdings(self._symbol, 1)
        elif close > upper and self._prev_close <= upper and self.portfolio.invested:
            self.liquidate()
        self._prev_close = close
'''
    else:
        raise ValueError(f"Unsupported LEAN strategy: {strategy}")

    return header + body


def _parse_stat_number(raw: Any) -> float | None:
    if raw is None:
        return None
    text = str(raw).strip().replace(",", "").replace("$", "")
    if not text or text.lower() in {"n/a", "nan", "none"}:
        return None
    if text.endswith("%"):
        text = text[:-1]
    try:
        return float(text)
    except ValueError:
        return None


def _stats_map(payload: dict[str, Any]) -> dict[str, str]:
    for key in ("Statistics", "statistics", "RuntimeStatistics", "runtimeStatistics"):
        block = payload.get(key)
        if isinstance(block, dict):
            return {str(k): str(v) for k, v in block.items()}
    return {}


def _find_result_json(output_dir: Path) -> Path | None:
    candidates = sorted(output_dir.glob("*.json"), key=lambda p: p.stat().st_mtime, reverse=True)
    for path in candidates:
        if path.name in {"config.json", "lean.json"}:
            continue
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            continue
        if _stats_map(data):
            return path
    return None


def _parse_lean_result(
    payload: dict[str, Any],
    *,
    symbol: str,
    strategy: str,
    start_date: str,
    end_date: str,
    initial_capital: float,
) -> dict[str, Any]:
    stats = _stats_map(payload)

    def pick(*keys: str) -> float | None:
        for key in keys:
            if key in stats:
                val = _parse_stat_number(stats[key])
                if val is not None:
                    return val
        return None

    total_return = pick("Net Profit", "Total Net Profit", "Total Performance")
    annualized = pick("Compounding Annual Return", "Annual Return", "Annualized Return")
    sharpe = pick("Sharpe Ratio", "Sharpe")
    max_dd = pick("Drawdown", "Max Drawdown", "Maximum Drawdown")
    win_rate = pick("Win Rate", "Winning Rate")
    total_trades = pick("Total Orders", "Total Trades", "Number of Trades")
    alpha = pick("Alpha", "α")
    benchmark = pick("Benchmark", "Benchmark Return", "Beta Benchmark")

    if total_return is None:
        end_equity = pick("End Equity", "Portfolio Value")
        if end_equity is not None and initial_capital:
            total_return = (end_equity - initial_capital) / initial_capital * 100

    total_trades_int = int(total_trades) if total_trades is not None else 0
    win_rate_val = win_rate if win_rate is not None else 0.0
    profitable = round(total_trades_int * win_rate_val / 100) if total_trades_int else 0

    total_return_val = total_return if total_return is not None else 0.0
    benchmark_val = benchmark if benchmark is not None else 0.0
    final_value = initial_capital * (1 + total_return_val / 100)

    return {
        "engine": "lean",
        "symbol": symbol,
        "strategy": strategy,
        "start_date": start_date,
        "end_date": end_date,
        "total_return": round(total_return_val, 2),
        "annualized_return": round(annualized or 0.0, 2),
        "sharpe_ratio": round(sharpe or 0.0, 2),
        "max_drawdown": round(abs(max_dd or 0.0), 2),
        "win_rate": round(win_rate_val, 1),
        "total_trades": total_trades_int,
        "profitable_trades": profitable,
        "buy_hold_return": round(benchmark_val, 2),
        "alpha": round(alpha if alpha is not None else total_return_val - benchmark_val, 2),
        "final_value": round(final_value, 2),
        "lean_statistics": stats,
    }


def _run_lean_backtest_sync(
    symbol: str,
    strategy: str,
    start_date: str,
    end_date: str,
    initial_capital: float,
) -> dict[str, Any]:
    if strategy not in STRATEGIES:
        raise ValueError(f"Unsupported strategy: {strategy}")

    status = get_status()
    if not status["available"]:
        raise RuntimeError(status["message"])

    workspace = _workspace_root()
    project = _project_dir()
    main_py = project / "main.py"
    main_py.parent.mkdir(parents=True, exist_ok=True)
    main_py.write_text(
        _algorithm_source(symbol, strategy, start_date, end_date, initial_capital),
        encoding="utf-8",
    )

    lean = _lean_executable()
    assert lean is not None

    with tempfile.TemporaryDirectory(prefix="iqt-lean-") as tmp:
        output_dir = Path(tmp)
        cmd = [
            lean,
            "backtest",
            PROJECT_NAME,
            "--output",
            str(output_dir),
            "--no-update",
        ]
        if _credentials_configured():
            cmd.append("--download-data")

        logger.info("Running LEAN backtest: %s", " ".join(cmd))
        result = subprocess.run(
            cmd,
            cwd=workspace,
            capture_output=True,
            text=True,
            timeout=settings.lean_backtest_timeout_seconds,
        )

        if result.returncode != 0:
            detail = (result.stderr or result.stdout or "LEAN backtest failed").strip()
            if "No data" in detail or "data file" in detail.lower():
                detail += (
                    "\n\nTip: Run ./scripts/setup-lean-mac.sh and ensure QuantConnect credentials "
                    "are configured (lean login) so LEAN can download market data."
                )
            raise RuntimeError(detail[-4000:])

        result_json = _find_result_json(output_dir)
        if not result_json:
            raise RuntimeError(
                "LEAN finished but no result JSON was found. "
                f"Check Docker logs. stdout tail:\n{(result.stdout or '')[-1500:]}"
            )

        payload = json.loads(result_json.read_text(encoding="utf-8"))
        parsed = _parse_lean_result(
            payload,
            symbol=symbol,
            strategy=strategy,
            start_date=start_date,
            end_date=end_date,
            initial_capital=initial_capital,
        )
        parsed["lean_job_id"] = result_json.stem
        return parsed


async def run_backtest(
    symbol: str,
    strategy: str,
    start_date: str,
    end_date: str,
    initial_capital: float,
) -> dict[str, Any]:
    return await asyncio.get_event_loop().run_in_executor(
        None,
        lambda: _run_lean_backtest_sync(
            symbol, strategy, start_date, end_date, initial_capital
        ),
    )
